trainingInput:
  scaleTier: CUSTOM
  # Configure a master worker with 2 P100 GPUs
  masterType: n1-standard-16
  masterConfig:
    acceleratorConfig:
      count: 2
      type: NVIDIA_TESLA_P100
  # Configure 2 workers, each with 2 P100 GPUs
  workerCount: 2
  workerType: n1-standard-16
  workerConfig:
    acceleratorConfig:
      count: 2
      type: NVIDIA_TESLA_P100