trainingInput:
  scaleTier: CUSTOM
  # Configure a master worker with 1 P100 GPUs
  masterType: n1-highmem-16
  masterConfig:
    acceleratorConfig:
      count: 1
      type: NVIDIA_TESLA_P100
  # Configure 0 workers, each with 0 P100 GPUs
  workerCount: 0
  workerType: n1-highmem-4
  workerConfig:
    acceleratorConfig:
      count: 0
      type: NVIDIA_TESLA_P100